#functino to go through and refresh data stored locally once per day
#each time a statistic is used/generated by other services, this will be called to check when the data was last grabbed
#if its been over a day, get new data, otherwise dont burden the APIs

